# Required license check to impose on Node repositories

name: required-license-check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Check for acceptable licenses
      uses: mikaelvesavuori/license-compliance-action@v1
      with:
        allow_licenses: "MIT;Apache-2.0"
